document.writeln("<html>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=gb2312\">");
document.writeln("<title>促销<\/title>");
document.writeln("<style type=\"text\/css\">");
document.writeln("<!--");
document.writeln(".style1 {color: #FF0000}");
document.writeln(".style3 {font-size: 16px}");
document.writeln(".style2 {font-size: 16px}");
document.writeln("-->");
document.writeln("<\/style>");
document.writeln("<\/head>");
document.writeln("");
document.writeln("<body>");
document.writeln("<span class=\"style1\">");
document.writeln("<script type=\"text\/javascript\">");
document.writeln("function GetRTime(){");
document.writeln("var EndTime= new Date(2015,3,3,0,0); ");
document.writeln("var NowTime = new Date();");
document.writeln("var nMS =EndTime.getTime() - NowTime.getTime();");
document.writeln("var nT=Math.floor(nMS\/(24*60*60*1000)-30);");
document.writeln("var nH=Math.floor(nMS\/(1000*60*60)) % 24;");
document.writeln("var nM=Math.floor(nMS\/(1000*60)) % 60;");
document.writeln("var nS=Math.floor(nMS\/1000) % 60;");
document.writeln("if(nS>= 0){");
document.writeln("document.getElementById(\"RemainT\").innerHTML=nT;");
document.writeln("document.getElementById(\"RemainH\").innerHTML=nH;");
document.writeln("document.getElementById(\"RemainM\").innerHTML=nM;");
document.writeln("document.getElementById(\"RemainS\").innerHTML=nS;");
document.writeln("}");
document.writeln("else {");
document.writeln("document.getElementById(\"CountMsg\").innerHTML=\"结束!!\";");
document.writeln("}");
document.writeln("setTimeout(\"GetRTime()\",1000);");
document.writeln("}");
document.writeln("window.onload=GetRTime;");
document.writeln("<\/script>");
document.writeln("<span class=\"style4\"><span class=\"style3\">活动公告：厂家促销，进口燕窝市场价2折清仓，特价抢购。春节送礼推荐！截止日期还剩下:<\/span><\/span><span class=\"style2\">");
document.writeln("<strong id=\"RemainT\"><\/strong>天");
document.writeln("<strong id=\"RemainH\"><\/strong>时");
document.writeln("<strong id=\"RemainM\"><\/strong>分");
document.writeln("<strong id=\"RemainS\"><\/strong>秒<\/span>");
document.writeln("<\/body>");
document.writeln("<\/html>");